---
- name: setup firewalld
  hosts: vagrant
  remote_user: admin
  become: true
  vars:
    ssh_port: 22/tcp
  tasks:
    # firewalld
    - name: start firewalld
      service: name=firewalld state=started enabled=yes

    - name: enable ssh port
      firewalld: port="{{ ssh_port }}" zone=public permanent=true state=enabled immediate=true

    - name: disable default ssh port
      firewalld: service=ssh zone=public permanent=true state=disabled immediate=true

    - name: enable httpd port
      firewalld: service=http zone=public permanent=true state=enabled immediate=true
      notify: reload firewalld

  handlers:
    - name: reload firewalld
      service: name=firewalld state=reloaded
