---
- name: setup LAMP
  hosts: vagrant
  remote_user: admin
  become: true
  vars:
    php_list:
      - php
      - php-mbstring
      - php-pear
    mariadb_list:
      - mariadb
      - mariadb-devel
      - mariadb-server
      - MySQL-python # For mysql module
    mariadb_root_password: toshi555
    ansible_hostname: 192.168.33.10
  tasks:
    # repository
    - name: add repository 'epel'
      yum: name=http://ftp.riken.jp/Linux/fedora/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present

    # Apache
    - name: install apache
      yum: name=httpd state=present
    - name: start httpd
      service: name=httpd state=started enabled=yes
  
    # PHP
    - name: install php
      yum: name={{ item }} state=present
      with_items: php_list

    # MariaDB
    - name: install MariaDB
      yum: name={{ item }} enablerepo=epel state=present
      with_items: mariadb_list
    - name: set config
      copy: src=../conf/server.cnf dest=/etc/my.cnf.d/server.cnf owner=root mode=0755
    - name: start mariadb
      service: name=mariadb state=started enabled=yes
    - name: Change root user password on first run
      mysql_user: name=root
                  password={{ mariadb_root_password }}
      ignore_errors: yes
    - name: remove root remote access
      mysql_user: login_user=root
                  login_password="{{ mariadb_root_password }}"
                  name=root
                  password={{ mariadb_root_password }}
                  priv=*.*:ALL,GRANT
                  host={{ item }}
      with_items:
        # 'localhost' needs to be the last item for idempotency, see
        # http://ansible.cc/docs/modules.html#mysql-user
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
    - name: delete anonymous MySQL server user for "{{ ansible_hostname }}"
      mysql_user: login_user=root login_password="{{ mariadb_root_password }}" user="" host="{{ ansible_hostname }}" state=absent
    - name: delete anonymous MySQL server user for localhost
      mysql_user: login_user=root login_password="{{ mariadb_root_password }}" user="" state=absent
    - name: remove the MySQL test database
      mysql_db: login_user=root login_password="{{ mariadb_root_password }}" db=test state=absent
