---
- name: setup admin user
  hosts: vagrant_init
  become: true
  vars:
    user_name: admin
    password: toshi555
    salt: salty
    ssh_key_pub: ../keys/fs_key.pub # To base playbook directory
    ssh_port: 22
  tasks:
    - name: create pass hash
    # MD5ではなくSHA512にすべき
      command: openssl passwd -salt {{ salt }} -1 {{ password }}
      register: pass_hash

    - name: add a new user
      user: name={{ user_name }} password={{ pass_hash.stdout }} state=present groups=wheel

    - name: allow wheel users to sudo
      # NOTE: Because of the ': ' on the line, fully quote or use {{':'}}.
      lineinfile: dest=/etc/sudoers regexp="^#\s*(%wheel\s+ALL=\(ALL\)\s+NOPASSWD{{':'}}\s+ALL)" line="\1" backrefs=yes state=present

    - name: register ssh key
      authorized_key: user={{ user_name }} key="{{ lookup('file', ssh_key_pub) }}"

    - name: change ssh port
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#Port " line="Port {{ ssh_port }}" state=present

    - name: disallow ssh root login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PermitRootLogin " line="PermitRootLogin no" state=present

    - name: disallow ssh password
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PasswordAuthentication " line="PasswordAuthentication no" state=present

    - name: allow RSAAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#RSAAuthentication " line="RSAAuthentication yes" state=present

    - name: allow PubkeyAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PubkeyAuthentication " line="PubkeyAuthentication yes" state=present
      notify: restart sshd

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
