---
- name: setup sshd
  hosts: vagrant_init
  become: true
  tasks:
    # firewalld
    - name: start firewalld
      service: name=firewalld state=started enabled=yes

    #- name: disable default ssh port
    #  firewalld: service=ssh zone=public permanent=true state=disabled immediate=true

    - name: enable ssh port
      firewalld: port="{{ ssh_port_fw }}" zone=public permanent=true state=enabled immediate=true
      notify: restart firewalld

    # sshd config
    - name: register ssh key
      authorized_key: user={{ user_name }} key="{{ lookup('file', ssh_key_pub) }}"

    - name: change ssh port
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#Port " line="Port {{ ssh_port }}" state=present

    - name: disallow ssh root login
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin " line="PermitRootLogin no" state=present

    - name: disallow ssh password
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PasswordAuthentication " line="PasswordAuthentication no" state=present

    - name: allow RSAAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#RSAAuthentication " line="RSAAuthentication yes" state=present

    - name: allow PubkeyAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PubkeyAuthentication " line="PubkeyAuthentication yes" state=present
      notify: restart sshd

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted

    - name: restart sshd
      service: name=sshd state=restarted
