---
- name: setup wordpress
  hosts: vagrant
  remote_user: "{{ remote_user_name }}"
  become: true
  tasks:
    - name: download wordpress
      get_url: url=https://ja.wordpress.org/latest-ja.tar.gz dest=/usr/share/wp.tar.gz mode=0777

    - name: unarchive
      unarchive: src=/usr/share/wp.tar.gz dest=/usr/share/ copy=no

    - name: remove downloaded wordpress archive
      file: path=/usr/share/wp.tar.gz state=absent

    - name: set apache config for wordpress
      copy: src=../conf/wordpress.conf dest=/etc/httpd/conf.d/wordpress.conf owner=root mode=0755
      notify: restart httpd

    - name: set htaccess for wp-config.php
      copy: src=../conf/htaccess dest=/usr/share/wordpress/.htaccess owner=apache mode=0755

    - name: change directory owner and group
      file: path=/usr/share/wordpress state=directory owner=apache group=apache recurse=yes

    - name: create mysql user for wordpress
      mysql_user: login_user=root
                  login_password="{{ mariadb_root_password }}"
                  name={{ mysql_wp_user }}
                  password={{ mysql_wp_user_pass }}
                  priv=*.*:ALL
                  state=present
                  host={{ item }}
      with_items:
        - '%'
        - 'localhost'

    - name: create db for wordpress
      mysql_db: login_user={{ mysql_wp_user }}
                login_password="{{ mysql_wp_user_pass }}"
                name={{ mysql_wp_db }}
                state=present
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
