---
- name: setup wordpress
  hosts: vagrant
  remote_user: admin
  become: true
  vars:
    mariadb_root_password: toshi555
    ansible_hostname: 192.168.33.10
    mysql_wp_user: wordpress
    mysql_wp_user_pass: toshi555
    mysql_wp_db: wordpress
  tasks:
    - name: install wordpress
      yum: name=wordpress state=present
      notify: restart httpd

    - name: set apache config for wordpress
      copy: src=../conf/wordpress.conf dest=/etc/httpd/conf.d/wordpress.conf owner=root mode=0755
      notify: restart httpd

    - name: change directory owner and group
      file: path=/usr/share/wordpress state=directory owner=apache group=apache recurse=yes

    - name: create mysql user for wordpress
      mysql_user: login_user=root
                  login_password="{{ mariadb_root_password }}"
                  name={{ mysql_wp_user }}
                  password={{ mysql_wp_user_pass }}
                  priv=*.*:ALL
                  state=present
                  host={{ item }}
      with_items:
        - '%'
        - 'localhost'

    - name: create db for wordpress
      mysql_db: login_user={{ mysql_wp_user }}
                login_password="{{ mysql_wp_user_pass }}"
                name={{ mysql_wp_db }}
                state=present
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
